spring:
  application.name: spring-demo
  profiles.active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: test
    password: test
  liquibase.change-log: /db/changelog/changelog.xml
server.port: 9000

prices.address: http://localhost:9001